name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Download dependencies
      run: go mod download
    
    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Files in cmd directory:"
        ls -la cmd/
        echo "Go files:"
        find . -name "*.go" -type f
    
    - name: Run tests
      run: go test ./...
    
    - name: Build
      run: go build -o k8s-gpu-analyzer ./cmd/k8s-gpu-analyzer
